// 사용자 데이터 관리 유틸리티 함수들

// 모든 사용자 가져오기
export const getAllUsers = () => {
  return JSON.parse(localStorage.getItem('users') || '[]')
}

// 현재 로그인한 사용자 가져오기
export const getCurrentUser = () => {
  const userData = sessionStorage.getItem('currentUser')
  return userData ? JSON.parse(userData) : null
}

// 지갑 주소로 사용자 찾기
export const getUserByWalletAddress = (walletAddress) => {
  const users = getAllUsers()
  return users.find(u => u.id === walletAddress || u.walletAddress === walletAddress)
}

// 지갑 주소로 사용자 생성
export const createWalletUser = (walletAddress) => {
  const users = getAllUsers()
  
  // 이미 존재하는지 확인
  const existingUser = getUserByWalletAddress(walletAddress)
  if (existingUser) {
    return existingUser
  }
  
  // 초대 코드 생성 (간단한 해시 기반)
  const generateInviteCode = (id) => {
    const hash = id.toString().split('').reduce((acc, char) => {
      return ((acc << 5) - acc) + char.charCodeAt(0)
    }, 0)
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789' // 0, O, I 제외
    let code = ''
    let num = Math.abs(hash)
    for (let i = 0; i < 6; i++) {
      code += chars[num % chars.length]
      num = Math.floor(num / chars.length)
    }
    return code
  }
  const inviteCode = generateInviteCode(walletAddress)
  
  // 새 사용자 생성
  const newUser = {
    id: walletAddress,
    walletAddress: walletAddress,
    loginType: 'wallet',
    inviteCode: inviteCode,
    createdAt: new Date().toISOString(),
    referrals: [],
    gameData: {
      level: 1,
      coins: 0,
      totalCoin: 0,
      catFragments: 50,
      nftCount: 0,
      miningLevel: 1,
      huntingLevel: 1,
      explorationLevel: 1,
      productionLevel: 1,
      miningCats: [null, null, null, null],
      huntingCats: [null, null, null, null],
      explorationCats: [null, null, null, null],
      productionCats: [null, null, null, null],
      inventory: []
    }
  }
  
  users.push(newUser)
  localStorage.setItem('users', JSON.stringify(users))
  
  return newUser
}

// 사용자 게임 데이터 업데이트
export const updateUserGameData = async (userId, gameData) => {
  const currentUser = getCurrentUser()
  
  // localStorage 방식
  const users = getAllUsers()
  const userIndex = users.findIndex(user => user.id === userId)
  
  if (userIndex !== -1) {
    users[userIndex].gameData = { ...users[userIndex].gameData, ...gameData }
    localStorage.setItem('users', JSON.stringify(users))
    
    // 현재 사용자 정보도 업데이트
    if (currentUser && currentUser.id === userId) {
      currentUser.gameData = { ...currentUser.gameData, ...gameData }
      sessionStorage.setItem('currentUser', JSON.stringify(currentUser))
    }
    
    return true
  }
  return false
}

// 사용자 코인 업데이트
export const updateUserCoins = (userId, coins) => {
  return updateUserGameData(userId, { coins })
}

// 사용자 토탈 코인 업데이트 (Coin C)
export const updateUserTotalCoin = (userId, totalCoin) => {
  return updateUserGameData(userId, { totalCoin })
}

// 동시에 포인트와 코인 업데이트
export const updateUserPointsAndCoins = (userId, coins, totalCoin) => {
  return updateUserGameData(userId, { coins, totalCoin })
}

// 사용자 레벨 업데이트
export const updateUserLevel = (userId, level) => {
  return updateUserGameData(userId, { level })
}

// 사용자 NFT 개수 업데이트
export const updateUserNFTCount = (userId, nftCount) => {
  return updateUserGameData(userId, { nftCount })
}

// 사용자 로그아웃
export const logoutUser = () => {
  sessionStorage.removeItem('currentUser')
}

// 사용자 데이터 초기화 (개발용)
export const clearAllUserData = () => {
  localStorage.removeItem('users')
  sessionStorage.removeItem('currentUser')
}

// 사용자 통계 가져오기
export const getUserStats = () => {
  const users = getAllUsers()
  return {
    totalUsers: users.length,
    totalCoins: users.reduce((sum, user) => sum + (user.gameData?.coins || 0), 0),
    averageLevel: users.length > 0 ? users.reduce((sum, user) => sum + (user.gameData?.level || 1), 0) / users.length : 0
  }
}

// 현재 언어 가져오기 (기본값: English, 한국어는 선택 옵션)
export const getCurrentLanguage = () => {
  const savedLang = localStorage.getItem('appLanguage')
  // 저장된 언어가 없거나 '한국어'인 경우 기본값 'English'로 강제 설정
  if (!savedLang || savedLang === '한국어') {
    localStorage.setItem('appLanguage', 'English')
    return 'English'
  }
  // 저장된 언어가 'English'인 경우 그대로 반환
  return savedLang
}

// 언어별 텍스트 가져오기
export const getI18nTexts = () => {
  const lang = getCurrentLanguage()
  
  return {
    ko: {
      home: '홈',
      game: '게임',
      exchange: '교환소',
      quest: '퀘스트',
      inventory: '인벤토리',
      factory: '제작소',
      mining: '채굴',
      hunting: '사냥',
      exploration: '탐험',
      production: '생산',
      back: '← 뒤로',
      settings: '설정',
      notification: '알림',
      login: '로그인',
      signup: '회원가입',
      email: '이메일',
      password: '비밀번호',
      loginButton: '로그인',
      signupButton: '회원가입',
      walletConnect: '지갑 연결',
      createCat: '데려 오기',
      catFragments: '고양이 파편',
      coin: '코인',
      point: '포인트',
      energy: '에너지',
      level: '레벨',
      complete: '완료',
      confirm: '확인',
      cancel: '취소',
      close: '닫기',
      success: '성공',
      error: '오류',
      loading: '로딩 중...',
      insufficient: '부족',
      required: '필수',
      optional: '선택',
      daily: '일일',
      weekly: '주간',
      monthly: '월간',
      quest: '퀘스트',
      reward: '보상',
      receive: '받기',
      received: '받음',
      inProgress: '진행 중',
      completed: '완료됨',
      buy: '구매',
      sell: '판매',
      shop: '상점',
      profile: '프로필',
      attendance: '출석체크',
      nft: 'NFT',
      inventory: '인벤토리',
      factory: '제작소',
      exchange: '교환소',
      settings: '설정',
      logout: '로그아웃',
      language: '언어',
      sound: '소리',
      vibration: '진동',
      totalPoints: '총 포인트',
      totalCoins: '총 코인',
      createCatSuccess: '고양이 데려오기 성공!',
      newCatAdded: '새로운 고양이가 인벤토리에 추가되었습니다!',
      enterEmail: '이메일을 입력해주세요',
      enterPassword: '비밀번호를 입력해주세요',
      enterAllFields: '모든 필드를 입력해주세요',
      loginError: '로그인 중 오류가 발생했습니다',
      invalidCredentials: '이메일 또는 비밀번호가 올바르지 않습니다',
      walletNotInstalled: 'MetaMask가 설치되어 있지 않습니다',
      installMetaMask: 'MetaMask를 설치하시겠습니까?',
      walletConnectFailed: '지갑 연결에 실패했습니다',
      walletConnectError: '지갑 연결 중 오류가 발생했습니다',
      insufficientCoins: '코인이 부족합니다',
      insufficientFragments: '고양이 파편이 부족합니다',
      insufficientPoints: '포인트가 부족합니다',
      insufficientEnergy: '에너지가 부족합니다',
      purchaseSuccess: '구매 완료!',
      purchaseFailed: '구매 실패',
      tradeSuccess: '거래 완료!',
      tradeFailed: '거래 실패',
      createSuccess: '제작 완료!',
      createFailed: '제작 실패',
      rewardReceived: '보상을 받았습니다',
      alreadyReceived: '이미 받은 보상입니다',
      questNotCompleted: '퀘스트를 완료하지 않았습니다',
      loginRequired: '로그인이 필요합니다',
      copySuccess: '복사되었습니다',
      saveSuccess: '저장되었습니다',
      saveFailed: '저장에 실패했습니다',
      common: '일반',
      rare: '레어',
      epic: '에픽',
      legendary: '레전더리',
      stars: '별',
      stats: '스탯',
      exp: '경험치',
      maxExp: '최대 경험치',
      levelUp: '레벨업',
      levelUpCost: '레벨업 비용',
      select: '선택',
      selected: '선택됨',
      filter: '필터',
      sort: '정렬',
      search: '검색',
      newest: '최신순',
      oldest: '오래된순',
      byLevel: '레벨순',
      byStars: '별순',
      byRarity: '레어리티순',
      byName: '이름순',
      all: '전체',
      miningEfficiency: '채굴 효율',
      huntingDamage: '사냥 데미지',
      explorationReward: '탐험 보상',
      productionSpeed: '생산 속도',
      strength: '근력',
      health: '체력',
      intelligence: '지능',
      dexterity: '손재주',
      courage: '용기',
      luck: '행운',
      earned: '획득',
      pointsEarned: 'point 획득!',
      fragmentsEarned: '고양이 파편',
      fragmentsEarnedCount: '개 획득!',
      miningComplete: '채굴 완료!',
      huntingComplete: '사냥 완료!',
      explorationComplete: '탐험 완료!',
      productionComplete: '생산 완료!',
      miningCatList: '채굴 냥이 목록',
      huntingCatList: '사냥 냥이 목록',
      explorationCatList: '탐험 냥이 목록',
      productionCatList: '생산 냥이 목록',
      levelUp: '레벨업!',
      progress: '진행',
      miningProgress: '채굴 진행',
      huntingProgress: '사냥 진행',
      explorationProgress: '탐험 진행',
      productionProgress: '생산 진행',
      miningSuccess: '채굴 성공!',
      oreFound: '광물 발견!',
      moneyEarned: '돈벌었다!',
      digMore: '더 파자!',
      monsterKilled: '몬스터 처치!',
      expEarned: '경험치 획득!',
      goldEarned: '골드 획득!',
      newAreaFound: '새 지역 발견!',
      treasureFound: '보물 획득!',
      adventureSuccess: '모험 성공!',
      mysteriousDiscovery: '신비한 발견!',
      craftComplete: '제작 완료!',
      itemCreated: '아이템 생성!',
      skillImproved: '기술 향상!',
      perfectWork: '완벽한 작품!',
      success: '성공!',
      good: '좋아!',
      complete: '완료!',
      amazing: '대박!',
      selectCat: '고양이 선택',
      removeCat: '고양이 제거',
      ownedPoints: '보유 포인트',
      ownedCoins: '보유 코인',
      exchangeRate: '거래가',
      buyCoinAmount: '구매할 코인 수량',
      sellCoinAmount: '판매할 코인 수량',
      requiredPoints: '필요 포인트',
      pointsToReceive: '받을 포인트',
      buyButton: '구매하기',
      sellButton: '판매하기',
      exampleAmount: '예: 1',
      coinBuy: 'Coin 구매',
      coinSell: 'Coin 판매',
      pointUsed: '사용한 포인트',
      pointReceived: '받은 포인트',
      inProgress: '진행중',
      completed: '완료',
      receive: '보상받기',
      rewardReceived: '보상 받기 완료!',
      earnedReward: '를 획득했습니다.',
      emptyInventory: 'Inventory is empty',
      totalItems: 'Total',
      items: 'items',
      searchAndFilter: 'Search & Filter',
      searchPlaceholder: 'Search by NFT name or ID...',
      starRating: 'Star Rating',
      levelFilter: 'Level',
      rarityFilter: 'Rarity',
      sortBy: 'Sort By',
      stars: 'Stars',
      levelHighToLow: 'Level (High to Low)',
      starsHighToLow: 'Stars (High to Low)',
      rarityHighToLow: 'Rarity (High to Low)',
      nameOrder: 'Name Order',
      reset: 'Reset',
      apply: 'Apply',
      stats: 'Stats',
      imageId: 'Image ID',
      createdAt: 'Created At',
      levelUpButton: 'Level Up',
      selectButton: 'Select',
      doubleClickDetail: 'Double-click for details',
      noNFTs: 'No NFTs',
      createCatInFactory: 'Create cats in the Factory!',
      selectedCharacter: 'Selected Character',
      cat: 'Cat',
      userSettings: '사용자 설정',
      walletConnection: '지갑 연결',
      connected: '연결됨',
      address: '주소',
      balance: '잔액',
      depositFromWallet: '지갑에서 충전하기',
      disconnect: '연결 해제',
      walletNotConnected: '지갑이 연결되지 않았습니다',
      walletConnectDesc: 'NFT 게임을 즐기려면 지갑을 연결해주세요',
      connecting: '연결 중...',
      attendance: '출석체크',
      doAttendanceCheck: '출석체크 하기',
      selectDepositMethod: '충전 방법 선택',
      selectExchangeToDeposit: '충전할 거래소를 선택해주세요',
      goToPhantomWallet: '팬텀 지갑으로 이동',
      goToUpbitExchange: '업비트 거래소로 이동',
      copyWalletAddressAndDeposit: '지갑 주소를 복사하여 거래소에서 입금하세요',
      copyWalletAddress: '지갑 주소 복사',
      walletConnected: '지갑이 연결되었습니다!',
      disconnectWalletConfirm: '지갑 연결을 해제하시겠습니까?',
      walletAddressCopied: '지갑 주소가 복사되었습니다!',
      copyFailed: '복사에 실패했습니다',
      refreshBalance: '잔액 새로고침',
      alreadyCheckedIn: '오늘 이미 출석체크를 완료했습니다!',
      checkInComplete: '출석체크 완료!',
      wallet: '지갑',
      energy100: '에너지 100',
      energy500: '에너지 500',
      energy1000: '에너지 1000',
      energy2000: '에너지 2000',
      energyRecover: '회복합니다',
      energyRecovered: '회복되었습니다',
      purchaseComplete: '구매 완료!',
      currentEnergy: '현재',
      loginRequired: '로그인이 필요합니다.',
      insufficientPoints: '포인트가 부족합니다.',
      insufficientCoins: '코인이 부족합니다.',
      purchaseFailed: '구매 실패. 다시 시도해주세요.',
      buy: '구매',
      back: '← 뒤로',
      mining: '채굴',
      miningLevel: '채굴 레벨',
      miningStart: '채굴 시작',
      miningInProgress: '채굴 중...',
      ownedResources: '보유 자원',
      stone: '돌',
      iron: '철',
      gold: '금',
      diamond: '다이아몬드',
      hunting: '사냥',
      playerInfo: '플레이어 정보',
      health: '체력',
      attack: '공격력',
      exp: '경험치',
      monsterSelection: '몬스터 선택',
      huntingStart: '사냥 시작',
      huntingInProgress: '사냥 중...',
      exploration: '탐험',
      explorationLevel: '탐험 레벨',
      explorationArea: '탐험 지역',
      undiscovered: '미발견',
      exploring: '탐험 중',
      explorationStart: '탐험 시작',
      explorationInProgress: '탐험 중...',
      explorationRewards: '탐험 보상',
      production: '생산',
      productionLevel: '생산 레벨',
      materialInventory: '재료 보유량',
      recipe: '제작 레시피',
      productionStart: '제작 시작',
      productionInProgress: '제작 중...',
      notification: '알림',
      markAllRead: '모두 읽음',
      noNotifications: '알림이 없습니다.',
      attendance: '출석체크',
      attendanceCheck: '출석체크',
      day: 'Day',
      attendanceComplete: '출석체크 완료!',
      pointsEarned: '포인트 획득!',
      alreadyCheckedToday: '오늘 이미 출석체크를 완료했습니다! 내일 다시 시도해주세요.',
      alreadyChecked: '이미 체크된 날짜입니다.',
      nextOrderOnly: '다음 순서의 출석체크만 가능합니다.',
      marketplace: '마켓플레이스',
      inviteFriends: '친구 초대',
      inviteCode: '초대 코드',
      copyInviteCode: '초대 코드 복사',
      shareKakao: '카카오톡으로 공유',
      inviteDescription: '친구를 초대하고 보상을 받으세요!',
      inviteReward: '초대 보상',
      inviteRewardDesc: '친구 1명 초대 시 100 포인트',
      newUserReward: '신규 가입 보상: 50 포인트',
      totalInvites: '총 초대',
      invites: '명',
      codeCopied: '초대 코드가 복사되었습니다!',
      shareSuccess: '카카오톡 공유가 완료되었습니다!',
      shareFailed: '카카오톡 공유에 실패했습니다.',
      inviteStats: '초대 통계',
      shareLink: '링크 공유',
      copyLink: '링크 복사',
      linkCopied: '링크가 복사되었습니다!',
      shareNative: '공유하기',
      myNFTs: '내 NFT',
      myListings: '내 판매',
      onSale: '판매 중',
      totalVolume: '총 거래량',
      itemsCount: '개',
      noNFTsInWallet: 'NFT가 없습니다',
      allRarity: '전체 레어리티',
      allPrice: '전체 가격',
      under1000Coins: '1,000 코인 미만',
      midPriceRange: '1,000 - 5,000 코인',
      over5000Coins: '5,000 코인 이상',
      oldest: '오래된순',
      priceLow: '가격 낮은순',
      priceHigh: '가격 높은순',
      levelHigh: '레벨 높은순',
      starsHigh: '별 등급 높은순',
      price: '가격',
      buy: '구매하기',
      noNFTsOnSale: '판매 중인 NFT가 없습니다',
      myNFTsCount: '내 NFT',
      ownedCoins: '보유 코인',
      sell: '판매하기',
      noNFTsAvailableForSale: '판매 가능한 NFT가 없습니다',
      mySalesList: '내 판매 목록',
      salePrice: '판매 가격',
      cancelSale: '판매 취소',
      noNFTsOnSaleList: '판매 중인 NFT가 없습니다',
      confirmCancelSale: '정말 판매를 취소하시겠습니까?',
      enterValidPrice: '올바른 가격을 입력해주세요.',
      loginRequired: '로그인이 필요합니다.',
      nftListedOnMarketplace: 'NFT가 마켓플레이스에 등록되었습니다!',
      saleCancelled: '판매가 취소되었습니다.',
      insufficientCoinsForPurchase: '코인이 부족합니다.',
      nftPurchased: 'NFT를 구매했습니다!',
      coinsPaid: '코인 지불',
      sellNFT: 'NFT 판매하기',
      starsRating: '성',
      sellPriceLabel: '판매 가격 (코인)',
      enterPrice: '가격을 입력하세요',
      currentOwnedCoins: '현재 보유 코인',
      cancel: '취소',
      registerSale: '판매 등록',
      buyNFT: 'NFT 구매하기',
      insufficientCoinsWarning: '코인이 부족합니다!',
      imageId: '이미지 ID',
      send: '전송하기',
      sendFeatureComingSoon: '전송 기능은 준비 중입니다.',
      buyFeatureComingSoon: '구매 기능은 준비 중입니다.',
      receive: '받기',
      receiveFeatureComingSoon: '받기 기능은 준비 중입니다.',
      searchNFT: '검색',
      searchPlaceholderNFT: 'NFT 이름 또는 ID로 검색...',
      reset: '초기화',
      apply: '적용'
    },
    en: {
      home: 'Home',
      game: 'Game',
      exchange: 'Exchange',
      quest: 'Quest',
      inventory: 'Inventory',
      factory: 'Factory',
      mining: 'Mining',
      hunting: 'Hunting',
      exploration: 'Exploration',
      production: 'Production',
      back: '← Back',
      settings: 'Settings',
      notification: 'Notification',
      login: 'Login',
      signup: 'Sign Up',
      email: 'Email',
      password: 'Password',
      loginButton: 'Login',
      signupButton: 'Sign Up',
      walletConnect: 'Connect Wallet',
      createCat: 'Create Cat',
      catFragments: 'Cat Fragments',
      coin: 'Coin',
      point: 'Point',
      energy: 'Energy',
      level: 'Level',
      complete: 'Complete',
      confirm: 'Confirm',
      cancel: 'Cancel',
      close: 'Close',
      success: 'Success',
      error: 'Error',
      loading: 'Loading...',
      insufficient: 'Insufficient',
      required: 'Required',
      optional: 'Optional',
      daily: 'Daily',
      weekly: 'Weekly',
      monthly: 'Monthly',
      quest: 'Quest',
      reward: 'Reward',
      receive: 'Receive',
      received: 'Received',
      inProgress: 'In Progress',
      completed: 'Completed',
      buy: 'Buy',
      sell: 'Sell',
      shop: 'Shop',
      profile: 'Profile',
      attendance: 'Attendance',
      nft: 'NFT',
      inventory: 'Inventory',
      factory: 'Factory',
      exchange: 'Exchange',
      settings: 'Settings',
      logout: 'Logout',
      language: 'Language',
      sound: 'Sound',
      vibration: 'Vibration',
      totalPoints: 'Total Points',
      totalCoins: 'Total Coins',
      createCatSuccess: 'Cat Created Successfully!',
      newCatAdded: 'A new cat has been added to your inventory!',
      enterEmail: 'Please enter your email',
      enterPassword: 'Please enter your password',
      enterAllFields: 'Please enter all fields',
      loginError: 'An error occurred during login',
      invalidCredentials: 'Email or password is incorrect',
      walletNotInstalled: 'MetaMask is not installed',
      installMetaMask: 'Would you like to install MetaMask?',
      walletConnectFailed: 'Failed to connect wallet',
      walletConnectError: 'An error occurred while connecting wallet',
      insufficientCoins: 'Insufficient coins',
      insufficientFragments: 'Insufficient cat fragments',
      insufficientPoints: 'Insufficient points',
      insufficientEnergy: 'Insufficient energy',
      purchaseSuccess: 'Purchase successful!',
      purchaseFailed: 'Purchase failed',
      tradeSuccess: 'Trade successful!',
      tradeFailed: 'Trade failed',
      createSuccess: 'Creation successful!',
      createFailed: 'Creation failed',
      rewardReceived: 'Reward received',
      alreadyReceived: 'Reward already received',
      questNotCompleted: 'Quest not completed',
      loginRequired: 'Login required',
      copySuccess: 'Copied successfully',
      saveSuccess: 'Saved successfully',
      saveFailed: 'Failed to save',
      common: 'Common',
      rare: 'Rare',
      epic: 'Epic',
      legendary: 'Legendary',
      stars: 'Stars',
      stats: 'Stats',
      exp: 'EXP',
      maxExp: 'Max EXP',
      levelUp: 'Level Up',
      levelUpCost: 'Level Up Cost',
      select: 'Select',
      selected: 'Selected',
      filter: 'Filter',
      sort: 'Sort',
      search: 'Search',
      newest: 'Newest',
      oldest: 'Oldest',
      byLevel: 'By Level',
      byStars: 'By Stars',
      byRarity: 'By Rarity',
      byName: 'By Name',
      all: 'All',
      miningEfficiency: 'Mining Efficiency',
      huntingDamage: 'Hunting Damage',
      explorationReward: 'Exploration Reward',
      productionSpeed: 'Production Speed',
      strength: 'Strength',
      health: 'Health',
      intelligence: 'Intelligence',
      dexterity: 'Dexterity',
      courage: 'Courage',
      luck: 'Luck',
      earned: 'Earned',
      pointsEarned: 'points earned!',
      fragmentsEarned: 'Cat Fragments',
      fragmentsEarnedCount: 'earned!',
      miningComplete: 'Mining Complete!',
      huntingComplete: 'Hunting Complete!',
      explorationComplete: 'Exploration Complete!',
      productionComplete: 'Production Complete!',
      miningCatList: 'Mining Cats',
      huntingCatList: 'Hunting Cats',
      explorationCatList: 'Exploration Cats',
      productionCatList: 'Production Cats',
      levelUp: 'Level Up!',
      progress: 'Progress',
      miningProgress: 'Mining Progress',
      huntingProgress: 'Hunting Progress',
      explorationProgress: 'Exploration Progress',
      productionProgress: 'Production Progress',
      miningSuccess: 'Mining Success!',
      oreFound: 'Ore Found!',
      moneyEarned: 'Money Earned!',
      digMore: 'Dig More!',
      monsterKilled: 'Monster Killed!',
      expEarned: 'EXP Earned!',
      goldEarned: 'Gold Earned!',
      newAreaFound: 'New Area Found!',
      treasureFound: 'Treasure Found!',
      adventureSuccess: 'Adventure Success!',
      mysteriousDiscovery: 'Mysterious Discovery!',
      craftComplete: 'Craft Complete!',
      itemCreated: 'Item Created!',
      skillImproved: 'Skill Improved!',
      perfectWork: 'Perfect Work!',
      success: 'Success!',
      good: 'Good!',
      complete: 'Complete!',
      amazing: 'Amazing!',
      selectCat: 'Select Cat',
      removeCat: 'Remove Cat',
      ownedPoints: 'Owned Points',
      ownedCoins: 'Owned Coins',
      exchangeRate: 'Exchange Rate',
      buyCoinAmount: 'Amount of Coins to Buy',
      sellCoinAmount: 'Amount of Coins to Sell',
      requiredPoints: 'Required Points',
      pointsToReceive: 'Points to Receive',
      buyButton: 'Buy',
      sellButton: 'Sell',
      exampleAmount: 'Ex: 1',
      coinBuy: 'Buy Coin',
      coinSell: 'Sell Coin',
      pointUsed: 'Points Used',
      pointReceived: 'Points Received',
      inProgress: 'In Progress',
      completed: 'Completed',
      receive: 'Claim Reward',
      rewardReceived: 'Reward Received!',
      earnedReward: 'earned.',
      emptyInventory: 'Inventory is empty',
      totalItems: 'Total',
      items: 'items',
      searchAndFilter: 'Search & Filter',
      searchPlaceholder: 'Search by NFT name or ID...',
      starRating: 'Star Rating',
      levelFilter: 'Level',
      rarityFilter: 'Rarity',
      sortBy: 'Sort By',
      stars: 'Stars',
      levelHighToLow: 'Level (High to Low)',
      starsHighToLow: 'Stars (High to Low)',
      rarityHighToLow: 'Rarity (High to Low)',
      nameOrder: 'Name Order',
      reset: 'Reset',
      apply: 'Apply',
      stats: 'Stats',
      imageId: 'Image ID',
      createdAt: 'Created At',
      levelUpButton: 'Level Up',
      selectButton: 'Select',
      doubleClickDetail: 'Double-click for details',
      noNFTs: 'No NFTs',
      createCatInFactory: 'Create cats in the Factory!',
      selectedCharacter: 'Selected Character',
      cat: 'Cat',
      userSettings: 'User Settings',
      walletConnection: 'Wallet Connection',
      connected: 'Connected',
      address: 'Address',
      balance: 'Balance',
      depositFromWallet: 'Deposit from Wallet',
      disconnect: 'Disconnect',
      walletNotConnected: 'Wallet is not connected',
      walletConnectDesc: 'Please connect your wallet to enjoy NFT games',
      connecting: 'Connecting...',
      attendance: 'Attendance Check',
      doAttendanceCheck: 'Do Attendance Check',
      selectDepositMethod: 'Select Deposit Method',
      selectExchangeToDeposit: 'Please select an exchange to deposit',
      goToPhantomWallet: 'Go to Phantom Wallet',
      goToUpbitExchange: 'Go to Upbit Exchange',
      copyWalletAddressAndDeposit: 'Copy wallet address and deposit at exchange',
      copyWalletAddress: 'Copy Wallet Address',
      walletConnected: 'Wallet connected!',
      disconnectWalletConfirm: 'Are you sure you want to disconnect your wallet?',
      walletAddressCopied: 'Wallet address copied!',
      copyFailed: 'Copy failed',
      refreshBalance: 'Refresh Balance',
      alreadyCheckedIn: 'You have already checked in today!',
      checkInComplete: 'Check-in complete! You received',
      wallet: 'Wallet',
      marketplace: 'Marketplace',
      myNFTs: 'My NFTs',
      myListings: 'My Sales',
      onSale: 'On Sale',
      totalVolume: 'Total Volume',
      itemsCount: 'items',
      noNFTsInWallet: 'No NFTs',
      allRarity: 'All Rarity',
      allPrice: 'All Price',
      under1000Coins: 'Under 1,000 Coins',
      midPriceRange: '1,000 - 5,000 Coins',
      over5000Coins: 'Over 5,000 Coins',
      oldest: 'Oldest',
      priceLow: 'Price Low',
      priceHigh: 'Price High',
      levelHigh: 'Level High',
      starsHigh: 'Stars High',
      price: 'Price',
      buy: 'Buy',
      noNFTsOnSale: 'No NFTs on sale',
      myNFTsCount: 'My NFTs',
      ownedCoins: 'Owned Coins',
      sell: 'Sell',
      noNFTsAvailableForSale: 'No NFTs available for sale',
      mySalesList: 'My Sales List',
      salePrice: 'Sale Price',
      cancelSale: 'Cancel Sale',
      noNFTsOnSaleList: 'No NFTs on sale',
      confirmCancelSale: 'Are you sure you want to cancel the sale?',
      enterValidPrice: 'Please enter a valid price.',
      loginRequired: 'Login required.',
      nftListedOnMarketplace: 'NFT listed on marketplace!',
      saleCancelled: 'Sale cancelled.',
      insufficientCoinsForPurchase: 'Insufficient coins.',
      nftPurchased: 'NFT purchased!',
      coinsPaid: 'coins paid',
      sellNFT: 'Sell NFT',
      starsRating: 'Stars',
      sellPriceLabel: 'Sale Price (Coins)',
      enterPrice: 'Enter price',
      currentOwnedCoins: 'Current Owned Coins',
      cancel: 'Cancel',
      registerSale: 'Register Sale',
      buyNFT: 'Buy NFT',
      insufficientCoinsWarning: 'Insufficient coins!',
      imageId: 'Image ID',
      send: 'Send',
      sendFeatureComingSoon: 'Send feature is coming soon.',
      buyFeatureComingSoon: 'Buy feature is coming soon.',
      receive: 'Receive',
      receiveFeatureComingSoon: 'Receive feature is coming soon.',
      searchNFT: 'Search',
      searchPlaceholderNFT: 'Search by NFT name or ID...',
      reset: 'Reset',
      apply: 'Apply',
      energy100: 'Energy 100',
      energy500: 'Energy 500',
      energy1000: 'Energy 1000',
      energy2000: 'Energy 2000',
      energyRecover: 'Recovers',
      energyRecovered: 'energy recovered',
      purchaseComplete: 'Purchase complete!',
      currentEnergy: 'Current',
      loginRequired: 'Login required.',
      insufficientPoints: 'Insufficient points.',
      insufficientCoins: 'Insufficient coins.',
      purchaseFailed: 'Purchase failed. Please try again.',
      buy: 'Buy',
      back: '← Back',
      mining: 'Mining',
      miningLevel: 'Mining Level',
      miningStart: 'Start Mining',
      miningInProgress: 'Mining...',
      ownedResources: 'Owned Resources',
      stone: 'Stone',
      iron: 'Iron',
      gold: 'Gold',
      diamond: 'Diamond',
      hunting: 'Hunting',
      playerInfo: 'Player Info',
      health: 'Health',
      attack: 'Attack',
      exp: 'EXP',
      monsterSelection: 'Monster Selection',
      huntingStart: 'Start Hunting',
      huntingInProgress: 'Hunting...',
      exploration: 'Exploration',
      explorationLevel: 'Exploration Level',
      explorationArea: 'Exploration Area',
      undiscovered: 'Undiscovered',
      exploring: 'Exploring',
      explorationStart: 'Start Exploration',
      explorationInProgress: 'Exploring...',
      explorationRewards: 'Exploration Rewards',
      production: 'Production',
      productionLevel: 'Production Level',
      materialInventory: 'Material Inventory',
      recipe: 'Recipe',
      productionStart: 'Start Production',
      productionInProgress: 'Producing...',
      notification: 'Notification',
      markAllRead: 'Mark All Read',
      noNotifications: 'No notifications.',
      attendance: 'Attendance',
      attendanceCheck: 'Attendance Check',
      day: 'Day',
      attendanceComplete: 'Attendance complete!',
      pointsEarned: 'points earned!',
      alreadyCheckedToday: 'Already checked in today! Please try again tomorrow.',
      alreadyChecked: 'Already checked.',
      nextOrderOnly: 'Only the next order can be checked.',
      inviteFriends: 'Invite Friends',
      inviteCode: 'Invite Code',
      copyInviteCode: 'Copy Invite Code',
      shareKakao: 'Share via KakaoTalk',
      inviteDescription: 'Invite friends and get rewards!',
      inviteReward: 'Invite Reward',
      inviteRewardDesc: '100 Points per friend invited',
      newUserReward: 'New User Reward: 50 Points',
      totalInvites: 'Total Invites',
      invites: 'friends',
      codeCopied: 'Invite code copied!',
      shareSuccess: 'Shared via KakaoTalk successfully!',
      shareFailed: 'Failed to share via KakaoTalk.',
      inviteStats: 'Invite Statistics',
      shareLink: 'Share Link',
      copyLink: 'Copy Link',
      linkCopied: 'Link copied!',
      shareNative: 'Share'
    }
  }[lang === '한국어' ? 'ko' : 'en']
}